services:
  setup:
    container_name: opensearch-cluster-setup
    profiles:
      - setup
    build:
      context: ./config/setup/
      args:
        OPENSEARCH_VERSION: ${OPENSEARCH_VERSION:-latest}
    init: true
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      SYSTEM_OS_DASHBOARD_PASSWORD: ${SYSTEM_OS_DASHBOARD_PASSWORD:-}
      OPENSEARCH_ADMIN_PASS: ${GLOBAL_ADMIN_PASS:-}
      OPENSEARCH_HOST: ${OPENSEARCH_HOST}
      CERT_STRENGTH: ${CERT_STRENGTH}
      CERT_DAYS: ${CERT_DAYS}
      CERT_SN: ${CERT_SN}
      CERT_DN: ${CERT_DN}
      OS_HOST: ${OPENSEARCH_HOST:-opensearch-node01}
      OS_PORT: ${OPENSEARCH_PORT:-9200}
    volumes:
      - ./stack-data/certificates:/certs
      - ./stack-data/certificates:/usr/share/opensearch/config/certificates:ro #This is mapped twice, once for the entrypoint to create the certificates, once for OpenSearch to be able to talk to the cluster
      - ./config/setup/config/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml:ro,Z
      - ./config/setup/config/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml:ro,Z
      - ./config/setup/config/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml:ro,Z
      - ./config/setup/config/roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml:ro,Z
      - ./config/setup/entrypoint.sh:/entrypoint.sh:ro,Z
    networks:
      - opensearch-net   
    depends_on:
      - opensearch-node01
      - opensearch-node02
      - opensearch-node03

  opensearch-node01:
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION:-latest}
    container_name: opensearch-node01
    restart: unless-stopped
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      node.name: opensearch-node01
      plugins.security.ssl.transport.pemkey_filepath: certificates/opensearch-node01/opensearch-node01.key # relative path
      plugins.security.ssl.transport.pemcert_filepath: certificates/opensearch-node01/opensearch-node01.pem
      plugins.security.ssl.http.pemkey_filepath: certificates/opensearch-node01/opensearch-node01.key
      plugins.security.ssl.http.pemcert_filepath: certificates/opensearch-node01/opensearch-node01.pem
      DISABLE_INSTALL_DEMO_CONFIG: "true"
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - "./config/opensearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "os-data1:/usr/share/opensearch/data"
      - ./stack-data/certificates:/usr/share/opensearch/config/certificates:ro
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    expose:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network


  opensearch-node02:
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION:-latest}
    container_name: opensearch-node02
    restart: unless-stopped
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      node.name: opensearch-node02
      plugins.security.ssl.transport.pemkey_filepath: certificates/opensearch-node02/opensearch-node02.key # relative path
      plugins.security.ssl.transport.pemcert_filepath: certificates/opensearch-node02/opensearch-node02.pem
      plugins.security.ssl.http.pemkey_filepath: certificates/opensearch-node02/opensearch-node02.key
      plugins.security.ssl.http.pemcert_filepath: certificates/opensearch-node02/opensearch-node02.pem
      DISABLE_INSTALL_DEMO_CONFIG: "true"
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - "./config/opensearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "os-data2:/usr/share/opensearch/data"
      - ./stack-data/certificates:/usr/share/opensearch/config/certificates:ro
    expose:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network


  opensearch-node03:
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION:-latest}
    container_name: opensearch-node03
    restart: unless-stopped
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      node.name: opensearch-node03
      plugins.security.ssl.transport.pemkey_filepath: certificates/opensearch-node03/opensearch-node03.key # relative path
      plugins.security.ssl.transport.pemcert_filepath: certificates/opensearch-node03/opensearch-node03.pem
      plugins.security.ssl.http.pemkey_filepath: certificates/opensearch-node03/opensearch-node03.key
      plugins.security.ssl.http.pemcert_filepath: certificates/opensearch-node03/opensearch-node03.pem
      DISABLE_INSTALL_DEMO_CONFIG: "true"
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - "./config/opensearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "os-data1:/usr/share/opensearch/data"
      - ./stack-data/certificates:/usr/share/opensearch/config/certificates:ro
    expose:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:${OPENSEARCH_VERSION:-latest}
    container_name: opensearch-dashboards
    restart: unless-stopped
    environment:
      DISABLE_INSTALL_DEMO_CONFIG: "true"
    volumes:
      - "./config/opensearch-dashboards/config/opensearch-dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml"
      - ./stack-data/certificates:/usr/share/opensearch-dashboards/config/certificates:ro
    ports:
      - 5601:5601
    networks:
      - opensearch-net 

  logstash:
    container_name: logstash
    build:
      context: ./config/logstash/
      args:
        LOGSTASH_VERSION: ${LOGSTASH_VERSION:-9.0.1}
    restart: unless-stopped
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      http.host: 0.0.0.0
      node.name: logstash
    volumes:
      - ./stack-data/certificates:/usr/share/logstash/config/certificates:ro
      - ./stack-data/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      - ./stack-data/logstash/grok-patterns:/usr/share/logstash/grok-patterns:ro,Z
      - ./stack-data/logstash/mappings:/usr/share/logstash/mappings:ro,Z
      - ./stack-data/ingest:/ingest:rw,Z
    ports:
      - 5044:5044
    networks:
      - opensearch-net


networks:
  opensearch-net:
    driver: bridge

volumes:
  os-data1:
  os-data2:
  os-data3:
