cluster.name: opensearch-cluster
network.host: 0.0.0.0

bootstrap.memory_lock: "true" # when combined with ulimits memlock settings, disables swapping.

cluster.routing.allocation.disk:
  threshold_enabled: true
  watermark.low: 93%
  watermark.high: 95%

discovery.seed_hosts: 
  - 'opensearch-node01'
  - 'opensearch-node02'
  - 'opensearch-node03'
cluster.initial_cluster_manager_nodes:
  - 'opensearch-node01'
  - 'opensearch-node02'
  - 'opensearch-node03'

plugins.security:
  # Uncomment the following two lines if you would like to store audit logs within OpenSearch.
#  audit:
#    type: internal_opensearch
  ssl:
    http:
      enabled: true
      clientauth_mode: OPTIONAL #Could be OPTIONAL or REQUIRED
      pemtrustedcas_filepath: certificates/ca/ca.pem
    transport:
      enabled: true
      pemtrustedcas_filepath: certificates/ca/ca.pem
      enforce_hostname_verification: false
  allow_unsafe_democertificates: false
  allow_default_init_securityindex: true
  authcz.admin_dn:
    - 'CN=ADMIN,O=QuirkyIT,L=BNE,ST=QLD,C=AU'
  nodes_dn:
    - 'CN=opensearch-node01,O=QuirkyIT,L=BNE,ST=QLD,C=AU'
    - 'CN=opensearch-node02,O=QuirkyIT,L=BNE,ST=QLD,C=AU'
    - 'CN=opensearch-node03,O=QuirkyIT,L=BNE,ST=QLD,C=AU'
  restapi:
    roles_enabled: ["all_access", "security_rest_api_access"]
    #password_validation_regex: '(?=.*[A-Z])(?=.*[^a-zA-Z\d])(?=.*[0-9])(?=.*[a-z]).{8,}'
    #password_validation_error_message: “Password must be minimum 8 characters long and must contain at least one uppercase letter, one lowercase letter, one digit, and one special character.”
  system_indices:
    enabled: true
    indices: [".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opendistro-asynchronous-search-response*"]

